In [38]:
import pandas as pd 
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import re

In [20]:
df = pd.read_csv("item_categories.csv") 
df_items = pd.read_csv("items.csv")
#df1 = pd.read_csv("items_b.csv")

In [21]:
df.head()

   item_category_id item_category_name_translated
0                 0    PC - Headsets / Headphones
1                 1             Accessories - PS2
2                 2             Accessories - PS3
3                 3             Accessories - PS4
4                 4             Accessories - PSP

# Extract main category, subcategory and subsubcategory of the "item_category_name" column

In [42]:
df["main_category"] = df["item_category_name_translated"].str.split("-", 1, expand=True) 
df["main_category"]

0                        PC
1               Accessories
2               Accessories
3               Accessories
4               Accessories
               ...
79                    Office
80                 Official
81    Clean carriers (spire)
82       Clean media (piece)
83        Elements of a food
Name: main_category, Length: 84, dtype: object

# Exercise 2 - apply text enc to the "item_name" column

In [24]:
df_items.head()

   item_id                               item_name_translated
0        0             !! IN THE POWER OF HAPPINESS (PLAST) D
1        1  ! ABBYY FineReader 12 Professional Edition Ful...
2        2              *** IN THE GLORY OF THE GLORY (UNV) D
3        3                             *** BLUE WAVE (Univ) D
4        4                                  *** BOX (GLASS) D

In [25]:
bow = CountVectorizer(ngram_range=(1, 1), max_df=10, min_df=2)
items_bow = bow.fit_transform(df_items["item_name_translated"])
tokens = bow.get_feature_names()
df1 = pd.DataFrame(data=items_bow.toarray(), columns=tokens)
df1

,00002,00003,00005,00008,00010,00011,00012,00013,00014,00016,...,ххквв,цифрова,цой,чехол,шансон,шарф,шуфутинский,эпик,эсхато,ёрш
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22165,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22166,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22167,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22168,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22169,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [26]:
df1.iloc[:,5228]

0        0
1        0
2        1
3        0
4        0
        ..
22165    0
22166    0
22167    0
22168    0
22169    0
Name: unv, Length: 22170, dtype: int64

In [27]:
print(items_bow)

  (2, 2205)	2
  (2, 5228)	1
  (5, 2262)	1
  (6, 2143)	1
  (7, 4509)	1
  (8, 4932)	1
  (9, 1873)	1
  (12, 2718)	1
  (12, 1933)	1
  (13, 4368)	1
  (14, 3961)	1
  (14, 3973)	1
  (15, 359)	1
  (17, 5086)	1
  (18, 832)	1
  (18, 904)	1
  (20, 1138)	1
  (21, 1097)	1
  (22, 1400)	1
  (26, 3378)	1
  (26, 4443)	1
  (27, 16)	1
  (28, 16)	1
  (29, 16)	1
  (30, 16)	1
  :	:
  (22138, 5560)	1
  (22141, 3313)	1
  (22143, 2065)	1
  (22144, 2066)	1
  (22145, 2066)	1
  (22148, 2055)	1
  (22149, 2055)	1
  (22150, 2055)	1
  (22151, 4384)	1
  (22152, 4384)	1
  (22154, 4384)	1
  (22155, 3873)	1
  (22155, 3874)	1
  (22156, 3873)	1
  (22156, 3874)	1
  (22157, 220)	1
  (22160, 1895)	1
  (22161, 5009)	1
  (22161, 380)	1
  (22164, 2100)	1
  (22165, 3542)	1
  (22166, 4047)	1
  (22167, 2772)	1
  (22167, 4047)	1
  (22168, 2622)	1

In [28]:
bow_2grams = CountVectorizer(ngram_range=(1, 2), max_df=10, min_df=2, dtype=np.int8)
items_bow_2grams = bow_2grams.fit_transform(df_items["item_name_translated"])
tokens_2grams = bow_2grams.get_feature_names()
df_2grams = pd.DataFrame(data=items_bow_2grams.toarray(), columns=tokens_2grams)
df_2grams

,000 space,00002,00002 microsoft,00003,00005,00008,00010,00011,00012,00013,...,шапка adventure,шапка assassin,шапка batman,шарф,шарф adventure,шуфутинский,шуфутинский михаил,эпик,эсхато,ёрш
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22165,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22166,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22167,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22168,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22169,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [29]:
tfidf = TfidfVectorizer(ngram_range=(1,1), max_df=10, min_df=2)
items_tfidf = tfidf.fit_transform(df_items["item_name_translated"])
tokens_tfidf = tfidf.get_feature_names()
df3 = pd.DataFrame(data=items_tfidf.toarray(), columns=tokens_tfidf)
df3

,00002,00003,00005,00008,00010,00011,00012,00013,00014,00016,...,ххквв,цифрова,цой,чехол,шансон,шарф,шуфутинский,эпик,эсхато,ёрш
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22165,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22166,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22167,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22168,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22169,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
tfidf_2 = TfidfVectorizer(ngram_range=(1,2), max_df=10, min_df=2)
items_tfidf_2 = tfidf_2.fit_transform(df_items["item_name_translated"])
tokens_tfidf_2 = tfidf_2.get_feature_names()
df4 = pd.DataFrame(data=items_tfidf_2.toarray(), columns=tokens_tfidf_2)
df4

,000 space,00002,00002 microsoft,00003,00005,00008,00010,00011,00012,00013,...,шапка adventure,шапка assassin,шапка batman,шарф,шарф adventure,шуфутинский,шуфутинский михаил,эпик,эсхато,ёрш
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22165,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22166,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22167,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22168,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22169,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0